package com.example.zamlingo.WordLibrary;

import java.util.HashMap;
import java.util.Map;;

import java.util.Map;

public class WordLibrary2 {
    private static final Map<String, String> NyanjaDictionary;

    static {

        NyanjaDictionary = new HashMap<>();
        // Add Nyanja translations
        NyanjaDictionary.put("yamba", "Amba - to begin.");
        NyanjaDictionary.put("ani", "Ani - what? What kind? What sort?");
        NyanjaDictionary.put("anthuh", "Anthu - people.");
        NyanjaDictionary.put("asamula", "Asamula - to yawn.");
        NyanjaDictionary.put("asilikali", "Asilikali - soldiers");
        NyanjaDictionary.put("ati", "Ati - isn't it? Don’t you? (asking for consent)");
        NyanjaDictionary.put("atsa", "Atsa - to kindle, to light.");
        NyanjaDictionary.put("apa", "Apa - here.");
        NyanjaDictionary.put("a", "A - there.");
        NyanjaDictionary.put("azimu", "Azimu - the spirits of the dead.");

        NyanjaDictionary.put("ba", "To steal. [see Kubera].");
        NyanjaDictionary.put("ba", "A verb tense infix indicating the time during which something is being done.");
        NyanjaDictionary.put("badisa", "To be born (as to time).");
        NyanjaDictionary.put("badili", "A relay, someone replacing another.");
        NyanjaDictionary.put("badwira", "Born (as to place).");
        NyanjaDictionary.put("bafuta", "White Calico or thin white linen.");
        NyanjaDictionary.put("bala", "To give birth, to produce (used of people, plants, animals).");
        NyanjaDictionary.put("bala", "A wound or an ulcer. [see Mabala and cironda].");
        NyanjaDictionary.put("bambo", "Father, Sir, Master.");
        NyanjaDictionary.put("bango", "Reeds. Matete (Ns).");
        NyanjaDictionary.put("bangula", "To roar (Lion), to shout.");
        NyanjaDictionary.put("banja", "Family, Relatives. (Li ndi Banja - he has got a Wife and Children).");
        NyanjaDictionary.put("basela", "A little extra gift you give to a customer who has bought goods from you.");
        NyanjaDictionary.put("basi", "That’s all, that’s enough, it’s enough.");
        NyanjaDictionary.put("bata", "Calm (no noise).");
        NyanjaDictionary.put("baya", "To stab, pierce (with a spear or any sharp instrument).");
        NyanjaDictionary.put("befu", "Being out of breath (cifuwa ca Befu Asthma).");
        NyanjaDictionary.put("bemberezi", "Mud wash.");
        NyanjaDictionary.put("bere", "Breast.");
        NyanjaDictionary.put("bereka", "To bear, to produce to have a child, to give birth, to carry a child on your back.");
        NyanjaDictionary.put("biliwila", "To be green (as new grass).");
        NyanjaDictionary.put("bingu", "Roar of thunder, noise of rapids, earthquake.");
        NyanjaDictionary.put("birimankhwe", "Chameleon.");
        NyanjaDictionary.put("bisa", "To hide something. [see - Bisya].");
        NyanjaDictionary.put("bisala", "To hide oneself. [see - Bisyala].");
        NyanjaDictionary.put("bodza", "A lie. Bodza = its a lie! Nena Bodza = to tell a lie. Cita bodza = to tell a lie. [see Nama = to tell a lie].");
        NyanjaDictionary.put("boma", "Fort, Government Offices, The Government (Administration).");
        NyanjaDictionary.put("bondo", "Knee.");
        NyanjaDictionary.put("bongo-bongo", "Brain.");
        NyanjaDictionary.put("boola", "To pierce, to drill a hole through. [see - Doola].");
        NyanjaDictionary.put("bovu", "Cheeks. [see - Masaya].");
        NyanjaDictionary.put("buluzi", "Lizard.");
        NyanjaDictionary.put("bunda", "Young bird. Young pigeons, the young of large birds. [see - Liunda].");
        NyanjaDictionary.put("busa", "To herd, to drive together.");
        NyanjaDictionary.put("busa", "Place for flock to rest or eat.");
        NyanjaDictionary.put("buthu", "A little girl who has not yet reached puberty.");
        NyanjaDictionary.put("buula", "To groan.");
        NyanjaDictionary.put("bvaka", "To clothe someone, to provide or give clothing. [see - Bveka].");
        NyanjaDictionary.put("bvala", "To put on clothes or to wear.");
        NyanjaDictionary.put("bveka", "To clothe someone: to provide or to give clothing. [see - Bvaka].");
        NyanjaDictionary.put("bvika", "To thatch.");
        NyanjaDictionary.put("bviika", "To dip, to put in water, to steep, to soak in water.");
        NyanjaDictionary.put("bvina", "To dance.");
        NyanjaDictionary.put("bvumbala", "To take out or to overturn.");
        NyanjaDictionary.put("bvomera", "To agree, to accept, to say ‘yes’. [see - Bvomereza & Bvomekeza].");
        NyanjaDictionary.put("bvula", "To take off clothes or to undress.");
        NyanjaDictionary.put("bvulala", "To be wounded or to be hurt.");
        NyanjaDictionary.put("bvulaza", "To hurt someone seriously or badly.");
        NyanjaDictionary.put("bvuma", "To give assent, to consent, to take up the chorus (when singing or telling a story). - Ku Bvuma - to give consent to something.");
        NyanjaDictionary.put("bvumbwe", "Wild cat.");
        NyanjaDictionary.put("bvumbwa", "To be wet with rain.");
        NyanjaDictionary.put("bvunda", "To be rotten [see - Vunda].");
        NyanjaDictionary.put("bvundikila", "To cover or to put a lid on.");
        NyanjaDictionary.put("bvundula", "To stir up.");
        NyanjaDictionary.put("bvundukula", "To uncover or to take lid off. [see - Vundukula].");
        NyanjaDictionary.put("bvuta", "To be difficult, to trouble, to worry, to bring difficulties.");
        NyanjaDictionary.put("bvutana", "To quarrel.");
        NyanjaDictionary.put("bvutika", "To be poor or to live in poverty.");
        NyanjaDictionary.put("bvuto", "Trouble, problem, difficulty.");
        NyanjaDictionary.put("bvuula", "To take out of the water.");
        NyanjaDictionary.put("bwalo", "Yard, ground around, courtyard, court.");
        NyanjaDictionary.put("bwanji", "How are you? How? What about (this or that).");
        NyanjaDictionary.put("bwato", "Boat.");
        NyanjaDictionary.put("bwebweta", "To babble, to stutter, to rave, to be delirious.");
        NyanjaDictionary.put("bwenzi", "1) (n) Friend. 2) (adv.) ought, should be, if only (used in the second part of a conditional sentence).");
        NyanjaDictionary.put("bwera", "To come. - Bwera ndi - to bring, to come with.");
        NyanjaDictionary.put("bwereka", "To borrow or to lend.");
        NyanjaDictionary.put("bwerekana", "To borrow or to lend to one another.");
        NyanjaDictionary.put("bwerera", "To return or to come back.");
        NyanjaDictionary.put("bwererana", "To come back together again.");
        NyanjaDictionary.put("bweretsa", "Lit. to make come; to cause, to order (a book), to bring, to go and get, to fetch.");
        NyanjaDictionary.put("bwereza", "To repeat or to do again.");
        NyanjaDictionary.put("bweza", "To give back, to send back.");
        NyanjaDictionary.put("bwinja", "Pl. mainja, a deserted place, an uninhabited or deserted village.");
        NyanjaDictionary.put("bwino", "Well, carefully, gently, later, in good time. Ku Cita Bwino Bwino - to be accurate.");
        NyanjaDictionary.put("bwinoko", "A bit better or rather well. [see Bwinopo].");
        NyanjaDictionary.put("bwinopo", "To chew cud.");
        NyanjaDictionary.put("bzola", "To pass through. [see Pyola].");

        NyanjaDictionary.put("celela", "To start off early in the morning. [see - Lawila or Lawilila].");
        NyanjaDictionary.put("cha", "1. To give a name, to be ripe (fruit), to pluck (fruit). 2. To set a trap.");
        NyanjaDictionary.put("chabe", "Useless. Nothing, only, just.");
        NyanjaDictionary.put("chaka", "Year or feast.");
        NyanjaDictionary.put("chakudya", "Something to eat or food.");
        NyanjaDictionary.put("Chala", "Finger or toe.");
        NyanjaDictionary.put("Chamba", "1. Indian hemp. 2. Dance (any).");
        NyanjaDictionary.put("Chambu", "Medicine for protecting gardens, camp, and house.");
        NyanjaDictionary.put("Chambuyo", "Backwards.");
        NyanjaDictionary.put("Changu", "Diligence. - Cita cangu, to be diligent.");
        NyanjaDictionary.put("Chanza", "Palm of your hand. - Gwirana canza, to shake hands.");
        NyanjaDictionary.put("Chapa", "To wash clothes.");
        NyanjaDictionary.put("Chaulere", "Gift (freely given).");
        NyanjaDictionary.put("Che", "Possessive stem: his, hers, its. [see - Ke].");
        NyanjaDictionary.put("Chedwa", "To delay, to be late, to linger.");
        NyanjaDictionary.put("Cheka", "To cut, to slice, to saw, to cut across.");
        NyanjaDictionary.put("Chembere", "Old woman. A married woman with children. [see - Ncembere].");
        NyanjaDictionary.put("Chenjera", "To be clever, to be cunning.");
        NyanjaDictionary.put("Chenjerera", "To outwit.");
        NyanjaDictionary.put("Chenjeretsa", "To ask for too high a price, to steal. To want to appear too clever in front of others.");
        NyanjaDictionary.put("Chenjeza", "To make clever, to warn in advance, to give good advice.");
        NyanjaDictionary.put("Chepa", "To be small, to be few in number, little, to be too few.");
        NyanjaDictionary.put("Chepetsa", "To diminish, to make small. [see - Kudzichepetsa].");
        NyanjaDictionary.put("Cheuka", "Turn around.");
        NyanjaDictionary.put("Chete", "Quietly, quiet, still.");
        NyanjaDictionary.put("Cheza", "To converse, to talk to, to chat to, to visit.");
        NyanjaDictionary.put("Cezela", "To visit. - Cezela usiku = to spend the whole night (doing something: e.g., dancing, drinking, traveling, etc.).");
        NyanjaDictionary.put("Chezima", "To shine, to gleam, to glitter. [see - Cezimira].");
        NyanjaDictionary.put("Chedwa", "1. To be called, to be named so and so. 2. To be late.");
        NyanjaDictionary.put("Cheru", "Attention. - Chita Cheru = to pay attention (to). Uzivelala = to pay attention to.");
        NyanjaDictionary.put("Chidindo", "A stamp seal or a date stamp.");
        NyanjaDictionary.put("Chire", "The bush. [see - thengo].");
        NyanjaDictionary.put("Chimwa", "To do wrong or to sin. [see - cimwa].");
        NyanjaDictionary.put("Chinga", "Fence or enclose with a fence.");
        NyanjaDictionary.put("Cholakwa", "Fault or mistake.");
        NyanjaDictionary.put("Chula", "1. To pronounce, to mention, or to say. 2. To lance, to open a boil.");
        NyanjaDictionary.put("Chibade", "Cranium, head, hard rind of a gourd.");
        NyanjaDictionary.put("Chibayo", "Pneumonia, Pleurisy.");
        NyanjaDictionary.put("Chibonga", "A club with a head or knobkerry.");
        NyanjaDictionary.put("Chiboo", "A hole, in cloth or wood.");
        NyanjaDictionary.put("Chibuma", "A clod of earth.");
        NyanjaDictionary.put("Chibvomezi", "Noise of an earthquake, of a crowd or of dancing.");
        NyanjaDictionary.put("Chibvundikiro", "Lid of a pot or container.");
        NyanjaDictionary.put("Chibwana", "Childishness or childhood.");
        NyanjaDictionary.put("Chibwano", "Chin.");
        NyanjaDictionary.put("Chibwebwe", "Stuttering, babbling or stammering.");
        NyanjaDictionary.put("Chibwenzi", "Friendship - pen pala Cibwenzi.");
        NyanjaDictionary.put("Chida", "Weapon.");
        NyanjaDictionary.put("Chidani", "Hatred.");
        NyanjaDictionary.put("Chidule", "Briefly or with brevity. Njira ya cidule = a short cut.");
        NyanjaDictionary.put("Chidulo", "Salt made from burnt ashes used in the same way as Bicarbonate of Soda.");
        NyanjaDictionary.put("Chiduka", "A broken piece (of brick) or its broken.");
        NyanjaDictionary.put("Chidutswa", "A bit cut or broken off something.");
        NyanjaDictionary.put("Chifukwa", "Because. - Chifukwa ca = because of. Chifukwa cace = the reason for it. Chifukwa ciani? = why?");
        NyanjaDictionary.put("Chifuwa", "Chest, a cold or a chest trouble.");
        NyanjaDictionary.put("Chifwamba", "A person who steals, a bandit, a thief. [see Kawalala].");
        NyanjaDictionary.put("Chigamba", "A patch.");
        NyanjaDictionary.put("Chigawo", "A part. [see - Gawa].");
        NyanjaDictionary.put("Chigololo", "Improper sexual conduct or adultery.");
        NyanjaDictionary.put("Chigumula", "1. A flood (water rising over its banks). 2. Retrenchment.");
        NyanjaDictionary.put("Chigwa", "A valley.");
        NyanjaDictionary.put("Chigayo", "Grinding mill.");
        NyanjaDictionary.put("Chikaso", "Yellow color of ginger.");
        NyanjaDictionary.put("Chikasu", "Ginger root.");
        NyanjaDictionary.put("Cikasu", "Yellow, the color of ginger. [see - Cikaso].");
        NyanjaDictionary.put("Chikho", "Gourd or cup (Chalice).");
        NyanjaDictionary.put("Chikhulupililo", "Trust, belief, or faith [see - khulupililia].");
        NyanjaDictionary.put("Chikole", "Something given as a pledge. [see - Mkole].");
        NyanjaDictionary.put("Chikoba", "Hide of an animal.");
        NyanjaDictionary.put("Chikondi", "Love.");
        NyanjaDictionary.put("Chikope", "Eyelids. [see - Kakope].");
        NyanjaDictionary.put("Chikumbumtima", "Memory or remembrance.");
        NyanjaDictionary.put("Chikunu", "Rape or abduction.");
        NyanjaDictionary.put("Chikwakwa", "Sickle, reaping-hook, the long hook-knife used as a grass cutter, a slasher. - (plur) Zikwakwa.");
        NyanjaDictionary.put("Chikwanje", "A large-bladed knife.");
        NyanjaDictionary.put("Chikwati", "Wedding. [see - Ukwati - marriage].");
        NyanjaDictionary.put("Chilakolako", "Extreme desire.");
        NyanjaDictionary.put("Chilala", "Drought, famine, destruction of food.");
        NyanjaDictionary.put("Chilankhulo", "Language. Lankhula - to speak. [see - Yankhula and Ciyankhulo].");
        NyanjaDictionary.put("Chilayo", "Vows.");
        NyanjaDictionary.put("Chilema", "A deformity, a maiming.");
        NyanjaDictionary.put("Chilimwe", "The dry season.");
        NyanjaDictionary.put("Chilombo", "A dangerous animal, a wild animal.");
        NyanjaDictionary.put("Chilumba", "An island.");
        NyanjaDictionary.put("Chimake", "A sheath.");
        NyanjaDictionary.put("Chimalo", "Brideprice or Bridewealth. Used by the Angoni People of Eastern Province.");

        NyanjaDictionary.put("da", "To be black, to be dark, to be dirty. [see - kufipa].");
        NyanjaDictionary.put("dabwa", "To be astonished.");
        NyanjaDictionary.put("dala", "Purposefully, intentionally, on purpose, knowingly.");
        NyanjaDictionary.put("dalitsa", "To cause to be blessed, happy.");
        NyanjaDictionary.put("dama", "Pride, pride of estate, also lust, impurity.");
        NyanjaDictionary.put("dambo", "A grass-covered plain, a watery marsh.");
        NyanjaDictionary.put("dana", "To hate one another.");
        NyanjaDictionary.put("dandaula", "To complain, to grumble, to grieve for.");
        NyanjaDictionary.put("dazi", "Baldness.");
        NyanjaDictionary.put("deka", "To settle (as water), to be calm of mind, to be quiet of heart.");
        NyanjaDictionary.put("denga", "Roof. [see tsindwi].");
        NyanjaDictionary.put("dere", "Like that [see - Tere: Conci].");
        NyanjaDictionary.put("dikira", "To wait, to wait for. [see - Lindira, Yembekeza].");
        NyanjaDictionary.put("dimba", "A garden near water. (Sugar-cane fields mostly grown in dimbas).");
        NyanjaDictionary.put("dinda", "To give a blow with your fist. To stamp - as with a date stamp.");
        NyanjaDictionary.put("diso", "Eye. pl. Maso [see - Liso: Meso].");
        NyanjaDictionary.put("diza", "To delay, to wait, to hesitate. – A type of large locust.");
        NyanjaDictionary.put("dodoma", "To be astonished, to be puzzled [see - Zizwa].");
        NyanjaDictionary.put("dondo", "Thick bush.");
        NyanjaDictionary.put("dongosola", "To arrange in order, to do in order, to speak in order.");
        NyanjaDictionary.put("dontha", "To drop, to leak.");
        NyanjaDictionary.put("dontho", "A drop.");
        NyanjaDictionary.put("dooko", "A landing place.");
        NyanjaDictionary.put("doola", "To pierce, to pass through. [see - Boola].");
        NyanjaDictionary.put("dothi", "Soil, earth. Mostly used in reference to rubbish or dirty surroundings.");
        NyanjaDictionary.put("pwanya", "To be broken in pieces, to break in pieces, to be cut.");
        NyanjaDictionary.put("dula", "To cut, to cut across, to take a short-cut.");
        NyanjaDictionary.put("dula Nkhani", "To interrupt.");
        NyanjaDictionary.put("dululu", "Snake poison.");
        NyanjaDictionary.put("dumbo", "fat.");
        NyanjaDictionary.put("duwa", "Pl. Maluwa flower.");
        NyanjaDictionary.put("dwiza", "To know.");

        NyanjaDictionary.put("e", "Yes.");
        NyanjaDictionary.put("ee", "Yes.");
        NyanjaDictionary.put("eya", "Yes.");
        NyanjaDictionary.put("edzeka", "To lean anything against (something). [see - yedzeka].");
        NyanjaDictionary.put("endi", "Same for all verbs beginning with `e` as: -enda = yenda, -enera = yenera, etc.");
        NyanjaDictionary.put("eni", "Plural of Mwini, -selves, owners.");
        NyanjaDictionary.put("enieni", "True, truly, really.");
        NyanjaDictionary.put("eti", "Isn't it? Don't you? (asking for consent). [See also: Ati? and Wati?].");

        NyanjaDictionary.put("afa", "To die, to be dead.");
        NyanjaDictionary.put("falitsa", "To spread about, to make known (as a rumour).");
        NyanjaDictionary.put("fanana", "To be similar, to resemble, to be like. [also - Fana fana].");
        NyanjaDictionary.put("fanizo", "A parable, a comparison.");
        NyanjaDictionary.put("fano", "An image, an idol.");
        NyanjaDictionary.put("fatsa", "To be kind, to be gentle, to be meek.");
        NyanjaDictionary.put("felela", "Thatch.");
        NyanjaDictionary.put("feluka", "To fail. [see - Lephera. -Jomba refers to getting stuck.]");
        NyanjaDictionary.put("fendaluzi", "The Luzi tree [see - Mbobvu or Nyanda].");
        NyanjaDictionary.put("fesa", "To sow (by scattering small seeds in the wind or seedbed).");
        NyanjaDictionary.put("fewa", "To be soft.");
        NyanjaDictionary.put("fika", "To arrive (at a place), to reach.");
        NyanjaDictionary.put("kufikira", "Until.");
        NyanjaDictionary.put("kufikira paka pa", "Until a certain date.");
        NyanjaDictionary.put("finya", "To squeeze, to twist, to press in order to get out pus (in a wound or boil), to squeeze water from clothes, to wring.");
        NyanjaDictionary.put("mafinya", "Pus.");
        NyanjaDictionary.put("fisi", "Hyena [see also - Cimbwi].");
        NyanjaDictionary.put("fiyira", "To be red or reddish. [see - Fuyira].");
        NyanjaDictionary.put("folera", "To spread the grass on the roof when thatching, to thatch.");
        NyanjaDictionary.put("fooka", "To be weak, to be spiritually weak.");
        NyanjaDictionary.put("fota", "To wither (as leaves, or a flower).");
        NyanjaDictionary.put("fotokoza", "To explain.");
        NyanjaDictionary.put("fufuza", "To grope for (something), search, investigate.");
        NyanjaDictionary.put("fuka", "To rise and spread, as smoke.");
        NyanjaDictionary.put("fuko", "People.");
        NyanjaDictionary.put("fukata", "To embrace, to carry a child on your breast.");
        NyanjaDictionary.put("fukula", "To dig, to dig up.");
        NyanjaDictionary.put("fula", "1) To dig a hole. 2) To castrate. 3) To forge (as a blacksmith). - [see also - Sula].");
        NyanjaDictionary.put("fulatira", "To turn your back on.");
        NyanjaDictionary.put("fulu", "Tortoise.");
        NyanjaDictionary.put("fulula", "Porridge of mixture water and flour.");
        NyanjaDictionary.put("fulumira", "To be in a hurry. [also - Fulumiza].");
        NyanjaDictionary.put("fuma", "To come from.");
        NyanjaDictionary.put("kufumila", "Come from = originate from.");
        NyanjaDictionary.put("fumbi", "Dust. [see - Pfumbi].");
        NyanjaDictionary.put("fuwbwa", "To be eaten (full of holes, as grain or wood).");
        NyanjaDictionary.put("funa", "To intend, to want, to seek, to desire, to be about to do something.");
        NyanjaDictionary.put("funa-funa", "To search for.");
        NyanjaDictionary.put("funda", "To be warm.");
        NyanjaDictionary.put("kufiundisa mazi", "Warming the water.");
        NyanjaDictionary.put("funga", "To lock.");
        NyanjaDictionary.put("koma cisko", "Fungulo - key.");
        NyanjaDictionary.put("fungata", "To put one's arms around.");
        NyanjaDictionary.put("fungatira", "To hug (as a mother hugs her child), to set on eggs (as a hen).");
        NyanjaDictionary.put("fungo", "A smell. Body odor.");
        NyanjaDictionary.put("funkha", "To carry off, to remove (in war), to plunder, to carry away everything.");
        NyanjaDictionary.put("funsa", "To inquire, to ask a question.");
        NyanjaDictionary.put("mwa ne funsira chani", "Why did you ask me?");
        NyanjaDictionary.put("funtha", "To become mad.");
        NyanjaDictionary.put("funya", "To fold, to roll up.");
        NyanjaDictionary.put("funyula", "To unfold.");
        NyanjaDictionary.put("fupa", "To give a reward (not payment), a free offering or gift. (often given at a dance or other ceremony). Also used in reference to bones.");
        NyanjaDictionary.put("fupi", "Short, near.");
        NyanjaDictionary.put("pafupi", "Close to, close by, easy to do.");
        NyanjaDictionary.put("fupika", "To be short, to be too short, to be near, to be close by.");
        NyanjaDictionary.put("futsa", "To parboil fresh vegetables and then dry them in the sun to preserve them for future use in the dry season. (Zofutsa).");
        NyanjaDictionary.put("fuula", "To scream. [see - Pfuula].");
        NyanjaDictionary.put("fuwa", "A cooking stone (one of the three used to support a pot over the fire).");
        NyanjaDictionary.put("fuyira", "To be red or reddish. [see - Fiyira].");
        NyanjaDictionary.put("fwidwa", "To be worn out, to be threadbare (of cloth).");

        NyanjaDictionary.put("gadama", "To lie on your back.");
        NyanjaDictionary.put("gaduka", "To boil (water), be boiling [see also - Wira].");
        NyanjaDictionary.put("gaga", "Bran, husk.");
        NyanjaDictionary.put("gaki", "Sisal.");
        NyanjaDictionary.put("gamuka", "To fall down (wall, hut).");
        NyanjaDictionary.put("gamula", "1) To cause to fall, to destroy. 2) To chop down a tree. 3) To decide, to give a verdict.");
        NyanjaDictionary.put("ganiza", "To think, to consider, to suppose.");
        NyanjaDictionary.put("ganizo", "A thought.");
        NyanjaDictionary.put("maganizo", "Thoughts.");
        NyanjaDictionary.put("ganyu", "A small bit of work to be paid on the spot. (piece work).");
        NyanjaDictionary.put("mkazi wa ganyu", "Prostitute.");
        NyanjaDictionary.put("munthu wa ganyu", "A person who does piece work.");
        NyanjaDictionary.put("ndikulembani ganyu", "I will write for you piece work.");
        NyanjaDictionary.put("gareta", "A cart.");
        NyanjaDictionary.put("garu", "A dog.");
        NyanjaDictionary.put("gaula", "To dig or plough the garden.");
        NyanjaDictionary.put("gawa", "To divide, to share out, to apportion.");
        NyanjaDictionary.put("gaya", "To grind.");
        NyanjaDictionary.put("gela/gera", "To shave, to cut your hair or beard.");
        NyanjaDictionary.put("gogo", "A grandparent.");
        NyanjaDictionary.put("gogoda", "To knock (e.g. on the door).");
        NyanjaDictionary.put("goli", "A slave-stick, a harness for oxen.");
        NyanjaDictionary.put("gombe", "The edge or bank of the river or lake.");
        NyanjaDictionary.put("gomola", "Sweet.");
        NyanjaDictionary.put("gona", "To lie down, to sleep, to stay long in a place. Ne wugona can even mean a person who is naturally dull.");
        NyanjaDictionary.put("goneka", "To lay down (as a child, a book).");
        NyanjaDictionary.put("gonja", "To do obeisance to, to submit to somebody. [Also: - Khonja].");
        NyanjaDictionary.put("gontha", "To be deaf (to be disabled).");
        NyanjaDictionary.put("gonthi", "A deaf person.");
        NyanjaDictionary.put("gowero", "A boy's house or dormitory.");
        NyanjaDictionary.put("guda", "A jar (large or small), a pail for water.");
        NyanjaDictionary.put("gudira", "To be wide and spreading, providing shade (tree).");
        NyanjaDictionary.put("guga", "To be threadbare (cloth), to be barren (old garden), to look old.");
        NyanjaDictionary.put("gula", "To buy.");
        NyanjaDictionary.put("gulitsa", "To sell.");
        NyanjaDictionary.put("gule", "A dance.");
        NyanjaDictionary.put("gulu", "A group of people or animals.");
        NyanjaDictionary.put("gulu la nkhondo", "The army, soldiers.");
        NyanjaDictionary.put("guluka", "To slip out (e.g. a hoe or an axe from its handle or tooth from its socket).");
        NyanjaDictionary.put("gulula", "To take out of its socket or from its handle, to dislocate.");
        NyanjaDictionary.put("gumuka", "To fall down (wall or plaster from the wall). [see Gamuka].");
        NyanjaDictionary.put("gund", "To hit, to bump into, to thunder.");
        NyanjaDictionary.put("gundika", "To be in full swing, to make a big noise - (gule wagundika).");
        NyanjaDictionary.put("guwa", "A platform, a kind of shelf made of clay in the house, altar.");
        NyanjaDictionary.put("gwa", "To fall, to collapse.");
        NyanjaDictionary.put("gwa", "Strong, hard, firm.");
        NyanjaDictionary.put("gwada", "To kneel down.");
        NyanjaDictionary.put("gwedza", "To shake, to be shaky, to be slack.");
        NyanjaDictionary.put("gwedeza", "To shake.");
        NyanjaDictionary.put("gwero", "A source, beginning of a river or stream.");
        NyanjaDictionary.put("gwira", "To catch, to hold, to grasp. Gwira nchito = to work.");
        NyanjaDictionary.put("gwirana", "To hold each other.");
        NyanjaDictionary.put("gwirizana", "To hold or to help one another.");
        NyanjaDictionary.put("gwirizira", "To support.");

        NyanjaDictionary.put("iai", "No [see Ai].");
        NyanjaDictionary.put("ife", "We.");
        NyanjaDictionary.put("ika", "To put, to place, to bury, to lay eggs (hen).");
        NyanjaDictionary.put("ima", "To stop moving, to stand still, to wait, to be in the early months of pregnancy.");
        NyanjaDictionary.put("imba", "To sing, to beat a drum [see Omba].");
        NyanjaDictionary.put("imbvi", "White hair, grey hair.");
        NyanjaDictionary.put("imfa", "Death.");
        NyanjaDictionary.put("imika", "To put upright, to stand upright.");
        NyanjaDictionary.put("imilila", "To stand, to stand upright, to stand by, to minister to.");
        NyanjaDictionary.put("inga", "To send away, to drive away, to frighten away (usually birds, goats or chickens).");
        NyanjaDictionary.put("insa", "A Duiker or small Antelope.");
        NyanjaDictionary.put("inwsa", "Collective singular for winged white ants.");
        NyanjaDictionary.put("inu", "You (2nd plural).");
        NyanjaDictionary.put("ipa", "To be bad, to be evil, (when one is ugly, one is said to be ‘ipa’ in the meaning of ‘ugly’, not of ‘bad’ and ‘evil’).");
        NyanjaDictionary.put("ipitsa", "To spoil, to ruin, to disfigure, to abuse, to do ill to.");
        NyanjaDictionary.put("itana", "To call, to invite, to summon.");
        NyanjaDictionary.put("iwala", "To forget.");
        NyanjaDictionary.put("iwe", "You (2nd person singular).");
        NyanjaDictionary.put("iwo", "They (3rd person plural).");
        NyanjaDictionary.put("iye", "He, she, it.");

        NyanjaDictionary.put("ja", "Demonstrative stem, for something easily identified or already mentioned. Also 'that over yonder', farther away.");
        NyanjaDictionary.put("jambula", "To draw (a picture), to print.");
        NyanjaDictionary.put("jenjemera", "To shiver, to tremble.");
        NyanjaDictionary.put("jolika", "To hold your head down, to be ashamed.");
        NyanjaDictionary.put("jujuka", "To fad, to lose its colour, to be worn out or threadbare.");
        NyanjaDictionary.put("jumpa", "To jump.");

        NyanjaDictionary.put("Ka", "Diminutive prefix, small or a verbal infix indicating motion.");
        NyanjaDictionary.put("Kada", "Verbal infix for past condition, would (have come), if...");
        NyanjaDictionary.put("Kabudula", "Short pants or underwear.");
        NyanjaDictionary.put("Kabvalidwe", "Manner of dressing or clothes.");
        NyanjaDictionary.put("Kabvira", "To splash over (as when carrying water), to spill.");
        NyanjaDictionary.put("Kabvumbulu", "A whirlwind.");

        NyanjaDictionary.put("Labada", "to care for, to head.");
        NyanjaDictionary.put("Labvula", "to spit.");
        NyanjaDictionary.put("Laka (1)", "to desire, long for. [see - Lakalaka]");
        NyanjaDictionary.put("Laka (2)", "to be baffled, puzzled, to fail, to be at a loss.");
        NyanjaDictionary.put("Alikuchita lakalakawo?", "Alikupa ndiwo.");
        NyanjaDictionary.put("Lakwa", "to be unskilful, awkward, to fail, miss, to be inaccurate.");
        NyanjaDictionary.put("Lalanje", "Orange, pl.Malanje.");
        NyanjaDictionary.put("Lalata", "to evil entreat, taut, speak harshly or evil to.");
        NyanjaDictionary.put("Lalika", "to proclaim, make known.");
        NyanjaDictionary.put("Lamba (1)", "belt, girdle.");
        NyanjaDictionary.put("Lamba (2)", "to pay respect, to do obeisance to, obey, stay under a chief.");
        NyanjaDictionary.put("Lambalala", "to skirt, to go around by the side of.");
        NyanjaDictionary.put("Lambula", "to order, to command, rule, decide.");
        NyanjaDictionary.put("Lamulo", "order, command, law.");
        NyanjaDictionary.put("Malamulo", "rule of law, set of rules, constitution.");
        NyanjaDictionary.put("Landa", "to seize, to take, snatch, to steal, to take by force.");
        NyanjaDictionary.put("Landira", "to receive.");
        NyanjaDictionary.put("Landitsa", "to set free, rescue.");
        NyanjaDictionary.put("Langa", "to punish, to admonish, to instruct.");
        NyanjaDictionary.put("Langiza", "to advise, to instruct.");
        NyanjaDictionary.put("Lankhula", "to speak, talk [see - Yankhula].");
        NyanjaDictionary.put("Lapa", "to regret, repent.");
        NyanjaDictionary.put("Lasa", "to hit, to wound, to shoot.");
        NyanjaDictionary.put("Nda Lasidwa ndi munga", "I have been pierced by a thorn.");
        NyanjaDictionary.put("Laula", "to utter bad things, unlawful, to swear (at a person), to meet with a bad omen (see Malaulo).");
        NyanjaDictionary.put("Lawa (1)", "to taste.");
        NyanjaDictionary.put("Lawa (2)", "to test, to try.");
        NyanjaDictionary.put("Lawi Malawi", "Flame of fire.");
        NyanjaDictionary.put("Lawira (1)", "to take leave, to say good-bye.");
        NyanjaDictionary.put("Lawira (2)", "to leave very early in the morning.");
        NyanjaDictionary.put("Payila", "its morning. [see - Lawirira].");
        NyanjaDictionary.put("Ledzera", "to be drunk- kuKulewa is the term mostly used. [see - Lodzera].");
        NyanjaDictionary.put("Leka", "to cease doing something, to stop.");
        NyanjaDictionary.put("Lekana", "to part, to separate, leave each other (husband and wife).");
        NyanjaDictionary.put("Lekerera", "to bear with, spare, not to take care of.");
        NyanjaDictionary.put("Lema", "to be tired.");
        NyanjaDictionary.put("Lemara", "to be lame. [see - Lumala] - Munthu wulemara.");
        NyanjaDictionary.put("Lemba", "to write, to draw, to engrave.");
        NyanjaDictionary.put("Lemkeza", "to honour, to respect.");
        NyanjaDictionary.put("Lemera (1)", "to be heavy.");
        NyanjaDictionary.put("Lemera (2)", "to be rich.");
        NyanjaDictionary.put("Cholemekra ngako!", "Kulemera!");
        NyanjaDictionary.put("Lenda", "to be gluey, sticky as some boiled leaves, gums.");
        NyanjaDictionary.put("Lenga", "to do wonders, create, to do things beyond power of man.");
        NyanjaDictionary.put("Lengeza", "to make known, proclaim, to send notice around.");
        NyanjaDictionary.put("Lephera", "to fail (to do something), to be at a loss [see - feluka].");
        NyanjaDictionary.put("Lera", "to care for, to nurse.");
        NyanjaDictionary.put("Leretsa", "to separate two combatants, to rescue from.");
        NyanjaDictionary.put("Lekura or Leluka", "to be not heavy, to be light [see Luluka and Pepuka].");
        NyanjaDictionary.put("Leta (Ns)", "to bring. - Letani mpindo.");
        NyanjaDictionary.put("Letsa", "to forbid, to hinder. - coletsa = hindrance.");
        NyanjaDictionary.put("Leza (1)", "God [Mlezi].");
        NyanjaDictionary.put("Leza (2)", "to be patient with, bear with. - Leza mtima = be patient.");
        NyanjaDictionary.put("Uta wa Leza", "rainbow.");
        NyanjaDictionary.put("Li", "to be.");
        NyanjaDictionary.put("Li ndi", "to have.");
        NyanjaDictionary.put("Libe", "to not have, to be without.");
        NyanjaDictionary.put("Licelo", "a flat basket (for winnowing).");
        NyanjaDictionary.put("Likha", "to hew down, to fall down, to knock down (a tree).");
        NyanjaDictionary.put("Likongwe", "a Weasel, a Ferret.");
        NyanjaDictionary.put("Lilime", "tongue [see - lulime].");
        NyanjaDictionary.put("Lima", "to hoe, cultivate, to use a hoe (khasu).");
        NyanjaDictionary.put("Limba", "to be hard, firm, strong.");
        NyanjaDictionary.put("Limba mtima", "be of a strong heart.");
        NyanjaDictionary.put("Limba", "a musical instrument, several strings strung on a board, harmonium, organ.");
        NyanjaDictionary.put("Limbika", "to be firm, strong.");
        NyanjaDictionary.put("Limodzi", "together [see - Pamodzi].");
        NyanjaDictionary.put("Linda", "to wait.");
        NyanjaDictionary.put("Lindira", "wait for, watch.");
        NyanjaDictionary.put("Lindimu", "Mandimu pl. - Lemon.");
        NyanjaDictionary.put("Linga (1)", "to aim, to purpose.");
        NyanjaDictionary.put("Linga (2)", "to measure, to think, to say.");
        NyanjaDictionary.put("Linga (3)", "a stockade, rampart.");
        NyanjaDictionary.put("Lingalira (1)", "to think [see - Ganiza].");
        NyanjaDictionary.put("Lingalira (2)", "to imagine.");
        NyanjaDictionary.put("lingana", "to be the same, similar.");
        NyanjaDictionary.put("Linganika", "to be equal.");
        NyanjaDictionary.put("Linganiza", "to make the same, to be equal, to make smooth, to level up.");
        NyanjaDictionary.put("Linthumbu", "the red ant [see - Linthumbwi].");
        NyanjaDictionary.put("Linunda", "the hump on the back of an animal [see - Nunda].");
        NyanjaDictionary.put("Lipa", "to pay, pay for [see - Lipira].");
        NyanjaDictionary.put("Lipenga", "a trumpet, bugle.");
        NyanjaDictionary.put("Lipira", "to pay, pay for (when buying), pay wages, repaying credit.");
        NyanjaDictionary.put("Lipsa", "to take revenge, to make pay for [see - lipsira].");
        NyanjaDictionary.put("Lira", "to cry, weep, sound (as bell).");
        NyanjaDictionary.put("Lira", "to cry for, want, need.");
        NyanjaDictionary.put("Litepo", "Matepo (plur) = leaf, leaves (of a tree).");
        NyanjaDictionary.put("Liti", "when?");
        NyanjaDictionary.put("Litsilo", "dirt.");
        NyanjaDictionary.put("Litsipa", "headache, swelling of the temple vein.");
        NyanjaDictionary.put("Liu", "a voice, tune (of a song) pl. Mau - words.");
        NyanjaDictionary.put("Liunda", "pl. Maunda, the young of large birds[see - bunda].");
        NyanjaDictionary.put("Liwiro", "speed.");
        NyanjaDictionary.put("Liwombo", "the fontanel (in the skull of an infant).");
        NyanjaDictionary.put("Lodza", "to bewitch. [see - Kulowa].");
        NyanjaDictionary.put("Lodzera", "to be drunk [see - ledzera].");
        NyanjaDictionary.put("Loko", "a lock.");
        NyanjaDictionary.put("Lola", "to allow, give permission.");
        NyanjaDictionary.put("Loleza", "to allow, give permission.");
        NyanjaDictionary.put("Lomba (1)", "to pray, worship.");
        NyanjaDictionary.put("Lomba (2)", "(Ns) now [see - tsopano].");
        NyanjaDictionary.put("Londa", "to watch, follow, pursue.");
        NyanjaDictionary.put("Londola", "to follow up, to pursue. Mwalondola mwana? = have you followed the child?");
        NyanjaDictionary.put("Longa (1)", "to arrange, to put to, to put one thing on top of another, in its place.");
        NyanjaDictionary.put("Longa (2)", "to pack things (in a suit case).");
        NyanjaDictionary.put("Longongeza", "to pack.");
        NyanjaDictionary.put("Longolola", "to quarrel, talk loudly.");
        NyanjaDictionary.put("Longosola", "to arrange, relate in order, one thing after another.");
        NyanjaDictionary.put("Lonjera", "to greet. Kupatsa moni is also to greet someone.");
        NyanjaDictionary.put("Lonjeza", "to promise, make agreement.");
        NyanjaDictionary.put("Losa", "to divine, to foretell.");
        NyanjaDictionary.put("Lota", "to dream, divine, guess. Analotela kuti chiza chitika = he guessed that it would happen.");
        NyanjaDictionary.put("Lowa", "to enter, to go in, come in [see - gena].");
        NyanjaDictionary.put("Lowana", "to live together.");
        NyanjaDictionary.put("Lowe", "a wet place in the ground.");
        NyanjaDictionary.put("Lowera", "cut in, in a queue.");
        NyanjaDictionary.put("Lowetsa", "to bring in [see - genetsa].");
        NyanjaDictionary.put("Loza", "to point towards.");
        NyanjaDictionary.put("Ludzu", "thirst [see - Njota].");
        NyanjaDictionary.put("Luka (1)", "to weave, to knit.");
        NyanjaDictionary.put("Luka (2)", "to vomit [see - Sanza].");
        NyanjaDictionary.put("Luluta", "to utter the sound of nthungululu.");
        NyanjaDictionary.put("Luluza", "to hush a child, to depreciate, to scorn, to make light of anyone.");
        NyanjaDictionary.put("Luma", "to bite.");
        NyanjaDictionary.put("Lumala", "to be lame [see - Lemara].");
        NyanjaDictionary.put("Lumba", "to thank (Tonga).");
        NyanjaDictionary.put("Lumbe", "to fall off, break.");
        NyanjaDictionary.put("Lumbwa", "dog.");
        NyanjaDictionary.put("Lungoma", "to make a plan.");

        NyanjaDictionary.put("Ma-", "(1) verbal infix, continuance, something often repeated.\n" +
                "(2) sign of respect when answering back, when an older person calls you.");
        NyanjaDictionary.put("Mabuka", "eruptions, swelling which come of themselves, on any part of the body, not directly traceable to external cause.");
        NyanjaDictionary.put("Mabvu", "wasps, hornets [see - mago].");
        NyanjaDictionary.put("Mabvume", "a chorus response in singing.");
        NyanjaDictionary.put("Macedzana", "(lit.) the year before, the year before last, a long time ago [see Makedzana].");
        NyanjaDictionary.put("Macila", "(1) a sedan-chair, a stretcher.\n(2) payment of a ransom, a ransom.");
        NyanjaDictionary.put("Madoda", "a mature man, sometimes headman, sing. Ndoda or Lidoda.");
        NyanjaDictionary.put("Madzi", "water.");
        NyanjaDictionary.put("Madzulo", "late afternoon, early evening.");
        NyanjaDictionary.put("Maere", "(1) wonders, things that astonish, are strange.\n(2) the ‘lots’.");
        NyanjaDictionary.put("Mafinya", "pus.");
        NyanjaDictionary.put("Mafuta", "fat or oil.");
        NyanjaDictionary.put("Mafuwa", "stones for cooking.");
        NyanjaDictionary.put("Maganizo", "thought(s). The action of thinking is expressed by the verb ‘kuganiza’.");
        NyanjaDictionary.put("Magazi", "blood [see - Mwazi].");
        NyanjaDictionary.put("Magwero", "head or source of river.");
        NyanjaDictionary.put("Mai", "Mother, my mother.");
        NyanjaDictionary.put("Maike", "his/her mother.");
        NyanjaDictionary.put("Mailo", "tomorrow/Yesterday.");
        NyanjaDictionary.put("Makaka", "kuchita to be proud, to show off.");
        NyanjaDictionary.put("Makamaka", "especially, surpassing [see - Maka].");
        NyanjaDictionary.put("Makama", "crowds [see - Magulu].");
        NyanjaDictionary.put("Makande", "black clay, soil.");
        NyanjaDictionary.put("Makangaza", "a fruit similar to pomegranate.");
        NyanjaDictionary.put("Makani", "a contest, in word or deed, rivalry, struggle.");
        NyanjaDictionary.put("Makedzana", "(lit.) the year before, the year before last, a long time ago [see Makedzana].");
        NyanjaDictionary.put("Makhalidwe", "nature, disposition, custom, habit.");
        NyanjaDictionary.put("Makhalo", "private parts of both men or women [see - Mapeto].");
        NyanjaDictionary.put("Makono", "nowadays, this present time, season, year.");
        NyanjaDictionary.put("Makwerero", "a ladder or steps.");
        NyanjaDictionary.put("Makwinya", "wrinkles on either clothes or face.");
        NyanjaDictionary.put("Mlalanje", "usually pl. for oranges, sing. Lilanje.");
        NyanjaDictionary.put("Malasha", "charcoal [see - Tsimbe].");
        NyanjaDictionary.put("Malaulo", "evil tidings [see - Laula].");
        NyanjaDictionary.put("Malaya", "pl. shirt or blouse.");
        NyanjaDictionary.put("Malemba", "Malambo - what is written, the scriptures.");
        NyanjaDictionary.put("Malimwe", "the dry season.");
        NyanjaDictionary.put("Malinga", "perhaps, supposing, if especially.\nMalinga ndi = according to.");
        NyanjaDictionary.put("Malipiro", "payment, wages, ransom.");
        NyanjaDictionary.put("Malike", "border, limit of your property.");
        NyanjaDictionary.put("Maliro", "funeral, mourning, a dead person.\nIka mailiro = to bury somebody.");
        NyanjaDictionary.put("Malisece", "nakedness.");
        NyanjaDictionary.put("Maliza", "to finish, but kusiliza is to finish.");
        NyanjaDictionary.put("Malo", "place, room, space.\nM`malo mwace = instead.\nKupatsa malo = to accommodate, or find a place for.");
        NyanjaDictionary.put("Malobvu", "spittle.");
        NyanjaDictionary.put("Malodza", "a portent, evil tidings, bewitchment.");
        NyanjaDictionary.put("Malonda", "sale, trade.\nZa malonda - things for sale.");
        NyanjaDictionary.put("Malonje", "what is given for reconciliation, also an offering to a visitor as lonjera.");
        NyanjaDictionary.put("Maloto", "pl. dream, but Lota is to dream.");
        NyanjaDictionary.put("Malowolo", "‘Lobola’ is bride-price.");
        NyanjaDictionary.put("Malome", "(maternal) uncle who is the head of the family. [see - Mtsibweni].");
        NyanjaDictionary.put("Malongo", "the joints, limbs, pain in, fever, malaria.");
        NyanjaDictionary.put("Mamba", "(1) the Cobra or black Mamba.\n(2) scales (fish).\n(3) dandruff.");
        NyanjaDictionary.put("Mambala", "good for nothing, bad boy, bad character.");
        NyanjaDictionary.put("Mame", "dew.");
        NyanjaDictionary.put("Mamina", "mucus from nose, -mina to blow one’s nose.");
        NyanjaDictionary.put("-mamvekera", "thunder.");
        NyanjaDictionary.put("-Mana", "to refuse to give something to someone, to be stingy.");
        NyanjaDictionary.put("Mancici", "a species of a large owl associated with witchcraft.");
        NyanjaDictionary.put("Manda", "grave or grave yard.");
        NyanjaDictionary.put("Mandimu", "usually pl. for lemons, sing. Ndimu or Lindimu.");
        NyanjaDictionary.put("Mandolo", "unripe ground-nuts.");
        NyanjaDictionary.put("Manga", "(1) to tie, to bind, fasten, build.\n(2) pots, stripes, variegated colours (of skin or cloth) (singular) Banga [see Mathotho].");
        NyanjaDictionary.put("Mang`a", "cracks on one’s heels, fissures.");
        NyanjaDictionary.put("Mangawa", "debts, what has to be paid when guilty in a case or mlundo.");
        NyanjaDictionary.put("Mangu", "quickly [see - Msanga].");
        NyanjaDictionary.put("Manja", "hands, sing. dzanja.");
        NyanjaDictionary.put("Manje", "now.");
        NyanjaDictionary.put("Manjenje", "palsy, trembling of the limb.");
        NyanjaDictionary.put("Mankhaka", "cucumbers [see - Makhaka].");
        NyanjaDictionary.put("Mankhusu", "the husk (wheat, rice, millet), what goes with the wind in winnowing.");
        NyanjaDictionary.put("Mano", "teeth but dzino or Lino for one tooth.");
        NyanjaDictionary.put("Mantha", "fear.\nku chita mantha = to be afraid.\nne wa mantha = he is a coward.");
        NyanjaDictionary.put("Manthongo", "sleep-dust in the corner of the eyes.");
        NyanjaDictionary.put("Manya", "wrinkles also known as Mankwinya.");
        NyanjaDictionary.put("Manyazi", "shame, shyness (though soni is more appropriate to shyness).\na chita manyazi = to be shy, ashamed.");

        NyanjaDictionary.put("-na-", "Verb infix, past tense.");
        NyanjaDictionary.put("-da-", "Verb infix, past tense.");
        NyanjaDictionary.put("-na", "And, with (used for ndi).");
        NyanjaDictionary.put("-na some", "Some, some more.");
        NyanjaDictionary.put("ina", "Another, other.");
        NyanjaDictionary.put("ena", "Some, others.");
        NyanjaDictionary.put("nadzikambe", "Chameleon.");
        NyanjaDictionary.put("-nai", "Four.");
        NyanjaDictionary.put("-nama", "To tell a lie.");
        NyanjaDictionary.put("namgumi", "A whale.");
        NyanjaDictionary.put("-Namiza", "To deceive, to slander.");
        NyanjaDictionary.put("namkholow", "Sweet-potato leaves used as ndiwo.");
        NyanjaDictionary.put("namkungwi", "Instructor, adviser during initiation rites.");
        NyanjaDictionary.put("namondwe", "A storm, a wind-storm, waves.");
        NyanjaDictionary.put("namsongole", "A species of grass, weed.");
        NyanjaDictionary.put("namtindi", "'Muchness, many, a multitude.");
        NyanjaDictionary.put("namwali", "A grown-up girl ready for marriage.");
        NyanjaDictionary.put("namwino", "A mid-wife.");
        NyanjaDictionary.put("nanga", "Yes, and how?, how about this?, well then.");
        NyanjaDictionary.put("namkalize", "A centipede (painful bite), sometimes also a scorpion.");
        NyanjaDictionary.put("ncafu", "The thigh, lap.");
        NyanjaDictionary.put("ncefu", "An eland, also nsefu.");
        NyanjaDictionary.put("ncembele", "A woman who has children.");
        NyanjaDictionary.put("ncence", "A fly.");
        NyanjaDictionary.put("ncenzi", "Large water rat, beaver rat.");
        NyanjaDictionary.put("ncetho", "An arrow with barbs.");
        NyanjaDictionary.put("ncisi", "A dirty person.");
        NyanjaDictionary.put("nchito", "Work, labour, occupation.");
        NyanjaDictionary.put("wanchito", "A worker, labourer.");
        NyanjaDictionary.put("ncofu", "(1) Colic, bile, vomiting. (2) Navel cord.");
        NyanjaDictionary.put("ndakatulo", "Something composed out of one's head.");
        NyanjaDictionary.put("ndalama", "Usually plural, money.");
        NyanjaDictionary.put("ndale", "A mode of wrestling men gripping each other, politics.");
        NyanjaDictionary.put("-ndandalika", "To stand or sit in line.");
        NyanjaDictionary.put("ndani", "Who is it?");
        NyanjaDictionary.put("ndebvu", "Beard.");
        NyanjaDictionary.put("madebvu", "A bearded person.");
        NyanjaDictionary.put("ndemanga", "Something composed out of one's head (as ndakatulo).");
        NyanjaDictionary.put("ndende", "Prison, jail.");
        NyanjaDictionary.put("ndeu", "Quarrel.");
        NyanjaDictionary.put("ndere", "Slime or moss.");
        NyanjaDictionary.put("ndi", "And, with, by; also to be.");
        NyanjaDictionary.put("ndipo", "And.");
        NyanjaDictionary.put("ndiponi", "It is acceptable, it is better, not too bad.");
        NyanjaDictionary.put("ndithu", "Really, indeed, in fact.");
        NyanjaDictionary.put("ndiwo", "Relish.");
        NyanjaDictionary.put("ndoda", "A mature man, plural madoda.");
        NyanjaDictionary.put("ndodo", "Stick.");
        NyanjaDictionary.put("ndoyo", "A bend, a corner.");
        NyanjaDictionary.put("ndowe", "Dung of animals, manure.");
        NyanjaDictionary.put("ndulu", "The gall, used to make poison.");
        NyanjaDictionary.put("nduna", "Adviser to the chief, war chief, a captain, government minister.");
        NyanjaDictionary.put("-nena", "To tell, say something.");
        NyanjaDictionary.put("-nenetsa", "Talk a little bit loudly.");
        NyanjaDictionary.put("-nenepa", "To be fat.");
        NyanjaDictionary.put("-neneza", "To accuse, slander, report a person.");
        NyanjaDictionary.put("-nga mine", "My. Mwana wanga = my child.");
        NyanjaDictionary.put("-nga-", "Verb infix to be able, even if.");
        NyanjaDictionary.put("-nga", "Verb to be like, similar.");
        NyanjaDictionary.put("ng'ala", "An opacity of the cornea.");
        NyanjaDictionary.put("ngala", "A head of grain, an ear of wheat.");
        NyanjaDictionary.put("ngalande", "A water channel, ditch.");
        NyanjaDictionary.put("ngalawa", "A canoe, a dug-out.");
        NyanjaDictionary.put("-ng'alula", "To split (bamboo, firewood).");
        NyanjaDictionary.put("-ng'amba", "To tear in pieces, split.");
        NyanjaDictionary.put("-ng'ambika", "To be torn.");
        NyanjaDictionary.put("chang'ambika", "It got torn.");
        NyanjaDictionary.put("ng'amba", "A break of fine weather in the rainy season.");
        NyanjaDictionary.put("ngamira", "A camel.");
        NyanjaDictionary.put("ngana", "So and so.");
        NyanjaDictionary.put("nganga", "Chest, breast-bone.");
        NyanjaDictionary.put("-ng'anima", "To shine, gleam, glitter.");
        NyanjaDictionary.put("cing'aning'ani", "Shining! Glitter!");
        NyanjaDictionary.put("-ng'anipa", "To gleam.");
        NyanjaDictionary.put("ng'anjo", "A furnace.");
        NyanjaDictionary.put("ng'anzi", "A species of large lizard, iguana.");
        NyanjaDictionary.put("-ngathe", "To be able, may, can.");
        NyanjaDictionary.put("ngati", "(1) If. (2) Like.");
        NyanjaDictionary.put("-ngati?", "How many? How much?");
        NyanjaDictionary.put("-ngo-", "(1) Verb infix to show that the action is performed without any particular reason; just, simply.");
        NyanjaDictionary.put("ngoli", "A one-stringed violin.");
        NyanjaDictionary.put("ngola", "A cart.");
        NyanjaDictionary.put("ngoma", "The kudu antelope.");
        NyanjaDictionary.put("ng'oma", "Drum (n).");
        NyanjaDictionary.put("ng'ombe", "A cow, bull, ox.");
        NyanjaDictionary.put("ng'oma", "Crocodile.");
        NyanjaDictionary.put("ngondia", "A corner, a bend.");
        NyanjaDictionary.put("ng'ondo", "Scattering.");
        NyanjaDictionary.put("-ng'ondoka", "To be dispersed.");
        NyanjaDictionary.put("ngondwa", "A large lizard.");
        NyanjaDictionary.put("ngongole", "A debt, a loan.");
        NyanjaDictionary.put("-ngongoleza", "To lend, borrow.");
        NyanjaDictionary.put("ngozi", "Accident, mishap.");
        NyanjaDictionary.put("ngozi inaoneka", "An accident happened.");
        NyanjaDictionary.put("nguli", "A top, whipping top.");
        NyanjaDictionary.put("Ng`ulung`unya", "To suck in the mouth without chewing.");
        NyanjaDictionary.put("Nguluwe", "A wild pig.");
        NyanjaDictionary.put("Ng`ung`udza", "To grumble, mutter, complain.");
        NyanjaDictionary.put("Nguwo", "Skin of animal, used as clothing or carrying a baby.");
        NyanjaDictionary.put("Ngwala", "A beaten track (of game).");
        NyanjaDictionary.put("Ngwalangwa", "A palm-fan.");
        NyanjaDictionary.put("Ngwandali", "Hoop iron (from around bales) used as grass slasher.");
        NyanjaDictionary.put("Ngwazi", "A big strong man, a brave warrior.");
        NyanjaDictionary.put("Ngwee", "The light at dawn, currency Kwacha - Ngwee.");
        NyanjaDictionary.put("Ngwiro", "Straight; prefect, without defect.");
        NyanjaDictionary.put("Nkhadze", "A species of Euphoria, a milky juice that causes blindness if it touches the eyes.");
        NyanjaDictionary.put("Nkafi", "An oar.");
        NyanjaDictionary.put("Nkhalamba", "An old person.");
        NyanjaDictionary.put("Nkhalamo", "A lion.");
        NyanjaDictionary.put("Nkhalango", "A forest, a thicket; woods.");

        NyanjaDictionary.put("Ocha", "To roast, toast; burn.");
        NyanjaDictionary.put("Chimanga Cho Ocha", "Roasted green maize.");
        NyanjaDictionary.put("Odzera", "To nod, sleep while sitting up.");
        NyanjaDictionary.put("Sinza", "Shut one's eyes.");
        NyanjaDictionary.put("Akustira", "He is falling asleep.");
        NyanjaDictionary.put("Oka", "To transplant.");
        NyanjaDictionary.put("Ola I", "To rot, decay [see - Vunda].");
        NyanjaDictionary.put("Ola II", "To gather and take away, something that is spilled or spread.");
        NyanjaDictionary.put("Oloka", "To cross, to ford (river).");
        NyanjaDictionary.put("Kuolowa Manja", "To be generous.");
        NyanjaDictionary.put("Omba", "To sound.");
        NyanjaDictionary.put("Omba Mfuti", "To fire a gun.");
        NyanjaDictionary.put("Omba Ng`oma", "Beat the drum.");
        NyanjaDictionary.put("Ombera", "To shoot at.");
        NyanjaDictionary.put("Ombeza", "To cast lots.");
        NyanjaDictionary.put("Ombola", "To ransom; rescue; redeem.");
        NyanjaDictionary.put("Omola", "To take out from pot with a spoon (portion of Nsima).");
        NyanjaDictionary.put("Ku Pakula Nsima", "Taking out a portion of nsima.");
        NyanjaDictionary.put("Ona", "To see, to look.");
        NyanjaDictionary.put("Oneka", "To see, to be visible, to happen.");
        NyanjaDictionary.put("Onekela", "To appear.");
        NyanjaDictionary.put("Onetsa", "To show.");
        NyanjaDictionary.put("Onda", "To be thin, lean. - Ne onda = he is thin.");
        NyanjaDictionary.put("Onga", "To thank. - Kuwanongera manja.");
        NyanjaDictionary.put("Onga Gun Powder", "[See - Wonga].");
        NyanjaDictionary.put("Ongeza", "To add [See - Onjeza].");
        NyanjaDictionary.put("Ongoka", "To be straight.");
        NyanjaDictionary.put("Ongola", "To make straight. - Kuongola Myendo = to stretch the legs.");
        NyanjaDictionary.put("Onja", "To take off a noose from an animal caught in a trap [see - Onjola].");
        NyanjaDictionary.put("Onjenza", "To add to; sometimes also - Onjeza.");
        NyanjaDictionary.put("Onjola", "To take off a noose from an animal trapped [see - Onja].");
        NyanjaDictionary.put("Ononja", "To destroy, spoil, waste.");
        NyanjaDictionary.put("Onongeka", "To be damaged, spoiled. - Cha onogeka = it's been damaged or spoiled.");
        NyanjaDictionary.put("Opa", "To fear, be afraid. - Ne mu opa = I am afraid of him.");
        NyanjaDictionary.put("Opsa/Opsya", "To cause to fear, to frighten, to be dreadful.");
        NyanjaDictionary.put("Otha Moto", "To warm yourself by the fire.");
        NyanjaDictionary.put("Othela Moto", "To warm oneself in the sun.");
        NyanjaDictionary.put("Owani", "A crested crane.");

        NyanjaDictionary.put("Sa", "(1) Not, verbal affix, also, si; (2) Related to master, master of [see - Tsa].");
        NyanjaDictionary.put("Sace", "A broom [see - Tsace].");
        NyanjaDictionary.put("Sadsa", "To lop off (a branch from a tree).");
        NyanjaDictionary.put("Sadzula", "To take off the husk, to skin, take the bark off.");
        NyanjaDictionary.put("Saganiza", "To mix, mingle, confuse [see - Sanganiza: Sakaniza].");
        NyanjaDictionary.put("Saka", "To hunt, to drive before one.");
        NyanjaDictionary.put("Sakaniza", "To mix [see - Saganiza: Sanganiza.]");
        NyanjaDictionary.put("Sakaza", "To destroy, spoil, devastate.");
        NyanjaDictionary.put("Sala", "(1) To abstain from, to fast, abstain from certain things. (2) To remain [see - Tsala].");
        NyanjaDictionary.put("Salala", "To be smooth.");
        NyanjaDictionary.put("Salaza", "To make smooth, to plane.");
        NyanjaDictionary.put("Samala", "To care, to take care of, to heed, to follow the customs. - Asamala nyumba = she takes care of the house.");
        NyanjaDictionary.put("Samba", "To bathe or wash oneself, used as euphemism for monthly period of a woman.");
        NyanjaDictionary.put("Sambira", "To swim [see - Nyaya].");
        NyanjaDictionary.put("Samuka", "To leave one place to go to another [see - Kukuka].");
        NyanjaDictionary.put("Sanduka", "To change into something or someone else. - Ana sanduka chinyama = he changed into a wild animal.");
        NyanjaDictionary.put("Sanduliza", "To change, turn over.");
        NyanjaDictionary.put("Sangalala", "To rejoice, be glad, to exult.");
        NyanjaDictionary.put("Sanja", "(1) To put upon the top, to be built upon. (2) To hammer, beat in order to sharpen.");
        NyanjaDictionary.put("Sanjika", "To put upon, to be put upon, to pile up.");
        NyanjaDictionary.put("Sankha", "To choose, separate. - Masanko = elections.");
        NyanjaDictionary.put("Sankhula", "To choose out from.");


    }

    public static String getNyanjaTranslation(String word) {
        return NyanjaDictionary.get(word.toLowerCase());
    }
}
